---
title: "Revue systématique de l'intervention ACT chez les etudiants"
author:
- Emma Weigel - Numéro étudiant 38011565
- Lisa Bernier - Numéro étudiant 40013232
date: 07.01.2022
output:
  pdf_document: default
  html_document: default
affiliation:
- institution: Université de Paris-Nanterre
bibliography: biblio_ACT_etudiants.bib
---

```{=html}
<style>
body {
text-align: justify}
</style>
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **Introduction**

La santé mentale des étudiants n'a jamais été aussi mauvaise, devenant un grave problème de santé publique [@copeland_impact_2021]. La population étudiante est deux fois plus à risque de développer des problèmes de santé mentale que la population générale [@bayram_prevalence_2008], et cela se traduit par une hausse des diagnostics de troubles psychologiques [@morin_processes_2021]. En effet, des études ont montré une augmentation alarmante des niveaux de détresse psychologique des étudiants [@american_college_health_association_national_2019 ; @gregoire_use_2018 ; @viskovich_randomized_2020] : ils rapportent un risque suicidaire plus élevé que les personnes diplômées et leurs performances et résultats scolaires sont considérablement impactés par le stress, l'épuisement, l'anxiété et la dépression [@edwards_novel_2019 ; @gregoire_ecological_2020 ; @howell_acceptance_2019 ; @lageborn_ongoing_2017]. Ainsi, le fonctionnement global des étudiants est influencé négativement par ce déficit de flexibilité psychologique décuplé lors de ces dernières années de pandémie mondiale [@bruffaerts_mental_2018 ; @charbonnier_etudiants_2021 ; @katajavuori_promoting_2021] provoquant une constante augmentation des demandes d'aides psychologiques [@gregoire_use_2018 ; @viskovich_randomized_2020]. Ces constatations montrent la nécessité du développement et de la mise en place de programmes d'intervention basés sur l'ACT à visée préventive, et permettant l'amélioration de la santé mentale des étudiants [@gregoire_use_2018 ; @rasanen_online_2016 ; @viskovich_randomized_2020].

La thérapie d'acceptation et d'engagement (ACT), issue de la troisième vague des thérapies cognitives et comportementales, est une intervention psychothérapeutique transdiagnostique relativement nouvelle. Elle utilise diverses composantes visant à accroître la flexibilité psychologique à travers six processus [@hayes_acceptance_2004]. Cette flexibilité psychologique a pour signification d'être pleinement en contact et être ouvert à son expérience du moment présent ainsi que savoir changer ou persister de comportement selon le contexte tout en respectant ses valeurs. Elle s'établit à partir des trois piliers qui inclut les six processus correspondant au modèle de l'hexaflex :

-   Le pilier ouvert se base sur l'acceptation des émotions et des pensées pénibles avec curiosité, détachement, non-réactivité et non-jugement. Une distance d'observation est établie avec les émotions et les pensées pénibles et l'expérience est utilisée pour agir au lieu des habitudes et des règles. Les processus présents sont *l'acceptation* et *la défusion*. L'acceptation correspond à accueillir notre expérience intérieure (la meilleure comme la pire) avec ouverture, curiosité et bienveillance, de sorte à retrouver une liberté de choix et d'action. La défusion est spéficiquement centrée sur les pensées : elle consiste à les prendre pour ce qu'elles sont, c'est-à-dire juste des pensées, et à remarquer qu'elles constituent un flux ininterrompu de va et vient, le plus souvent de façon inconsciente. Ces pensées sont le fruit de la rencontre entre notre histoire passée et le contexte actuel.
-   Le pilier conscient se focalise sur *l'attention flexible du moment présent* et sur *le soi observateur*. L'attention flexible du moment présent signifie être capable de porter son attention là où cela est le plus efficace dans la situation. Le soi observateur est être conscient de ce qui se passe : nous avons une position d'observation en nous, une position de conscience qui reste constante, inchangée là où tout le reste, (comme nos émotions, notre corps) change et évolue.
-   Le pilier engagé se concentre sur les comportements basés sur les valeurs, sur les comportements flexibles ou persévérants basés sur les contingences réelles et sur l'acceptation de la vulnérabilité qui va avec les valeurs. *Les valeurs* sont les qualités d'action sources de satisfaction par elles-mêmes et donnant du sens à la vie. *L'action engagée* correspond à toutes les actions observables étant cohérentes avec nos valeurs.

L'ACT permet ainsi aux individus de vivre pleinement et sans évitement les émotions et les sensations « problèmes » en les acceptant plutôt qu'en tentant la modification ou la réduction de celles-ci [@levin_web-based_2017]. En effet, la flexibilité psychologique ayant un rôle accru dans la promotion du bien-être émotionnel, psychologique et social [@edwards_novel_2019 ; @rasanen_online_2016], le développement de telles compétences chez les étudiants contribue à la prévention et à la diminution des problèmes de santé mentale [@viskovich_randomized_2020].

Ainsi, les interventions visant la flexibilité psychologique, telles que l'ACT, permettent d'améliorer le bien-être des étudiants, ainsi que leurs performances académiques [@edwards_novel_2019 ; @howell_acceptance_2019 ; @katajavuori_promoting_2021 ; @rasanen_online_2016]. En effet, les étudiants participant à des interventions ACT signalent une diminution des symptômes de stress, de détresse, d'anxiété et de dépression [@danitz_mindful_2016 ; @edwards_novel_2019 ; @gregoire_use_2018 ; @katajavuori_promoting_2021 ; @morin_processes_2021].

Face au mal-être étudiant, il est primordial de promouvoir une plus grande flexibilité psychologique, et ainsi garantir leur bien-être général. En tant qu'approche transdiagnostique, l'ACT peut agir sur un large éventail de défis et problèmes académiques et personnels rencontrés par les étudiants [@danitz_mindful_2016 ; @katajavuori_promoting_2021]. Elle doit être utilisée, à usage préventif ou pour une symptomatologie installée, d'autant plus que sa nature transdiagnostique se montre particulièrement bien adaptée au milieu universitaire [@levin_web-based_2017].

Toutefois, selon la récente méta-analyse de @howell_acceptance_2019, il reste encore à étudier davantage les effets des interventions de l'ACT afin d'analyser de façon plus approfondie leurs effets sur le bien-être des étudiants. De plus, depuis celle-ci, la situation étudiante n'a fait qu'empirer [@coquard_les_2021]. Après ces dernières années d'enseignements à distance sans interaction sociale ou lieu ouvert pour nombres de pays, une forte augmentation des niveaux d'anxiété, de dépression, et de détresse psychologique a été observée chez les étudiants [@essadek_mental_2020 ; @son_effects_2020]. Ce grave problème de santé publique atteint un point critique où les demandes d'aides psychologiques dans les universités et en ville ont augmentées de façon exponentielle, faisant ainsi preuve d'un besoin d'aide et de reconnaissance de cette situation par les étudiants [@holm-hadulla_well-being_2021].

De ce fait, l'objectif principal de cette recherche est d'étudier la thérapie d'acceptation et d'engagement comme une intervention de soutien et de compréhension (et non de prise en charge) pour lutter contre la détresse psychologique des étudiants.

# **Références**
